# Generated by Django 3.1 on 2022-12-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_pokemon_title_jp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolved_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pokemon_entities.pokemon'),
            preserve_default=False,
        ),
    ]
