# Generated by Django 3.1 on 2022-12-22 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20221221_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolved_from',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='Эволюционный предшественник'),
        ),
    ]
